### ISSUE TITLE
Release Checklist - v7.9.3

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4438]
### Pre-Release Tasks:

-  [x] Meet in the development meeting to decide which issues will be included in the release
   - [x] Assess problems to determine their alignment with our current timeline
   - [x] Identify user issues and assess their urgency
-  [x] Complete development required to resolve all issues included in the milestone
-  [x] Test all pull requests included in the milestone and respond to feedback from the testing team
-  [x] Bring the release milestone to 0 issues
-  [x] Perform general testing to validate the release candidate
    - [x] Verify that the checklist has been completed by 3 members of the testing staff
    - [x] Address any problems identified during testing and respond accordingly
-  [x] Update or create documentation related to this release
-  [x] Create a release notes topic on Discourse and share with the testing team
-  [x] Create a tag and release the update on GitHub

### Post-Release Tasks:

-  [x] Update Specify Cloud and other SCC-managed deployments
   -  [x] Verify deployments are functioning as intended and monitor feedback from users
-  [x] Close the release milestone on GitHub
-  [x] Merge pull requests in the next release milestone into `production`
-  Update development dependencies to their latest compatible versions
   - N/A as we have 7.9.4 waiting - but this should definitely be done after 7.9.4 is out
-  Review and merge any pending pull requests to prevent them from becoming stale
   - N/A as we have 7.9.4 waiting - but this should definitely be done after 7.9.4 is out
